version: "3"
services: 
  database:
    image: postgres:13.1-alpine
    restart: always
    env_file: 
      - database.env
    ports: 
      - "5432:5432"
    volumes: 
      - pg-data:/var/lib/postgresql/data/

volumes: 
  pg-data: